-- liquibase formatted sql
insert into public.attributes (id, name)
values
    (1, 'Rom Memory'),
    (2, 'Ram Memory'),
    (3, 'Color'),
    (4, 'Display diagonal'),
    (5, 'Screen resolution'),
    (6, 'Screen type'),
    (7, 'Screen refresh rate'),
    (8, 'Glass protection technology'),
    (9, 'Communication standards'),
    (10, 'Number of SIM cards'),
    (11, 'SIM card size'),
    (12, 'Operating system'),
    (13, 'Processor frequency'),
    (14, 'Number of processor cores'),
    (15, 'Processor model'),
    (16, 'Flesh card'),
    (17, 'Main camera resolution'),
    (18, 'Video card'),
    (19, 'Bluetooth version'),
    (20, 'Weight'),
    (21, 'Max play time'),
    (22, 'Model'),
    (23, 'Camera MP');
